package progra1examen2isaacreyeschavarria;

import java.util.HashSet;
import java.util.Random;
import java.util.Set;
import javax.swing.JOptionPane;

public class principal extends javax.swing.JFrame {

    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        tnencuesta = new javax.swing.JTextField();
        lnombre = new javax.swing.JLabel();
        tnombre = new javax.swing.JTextField();
        ledad = new javax.swing.JLabel();
        tedad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tcorreo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rsi = new javax.swing.JRadioButton();
        rno = new javax.swing.JRadioButton();
        bregistrar = new javax.swing.JButton();
        bimprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("numero de encuesta: ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 140, 40);

        tnencuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnencuestaActionPerformed(evt);
            }
        });
        getContentPane().add(tnencuesta);
        tnencuesta.setBounds(240, 20, 150, 30);

        lnombre.setText("nombre y apellido: ");
        getContentPane().add(lnombre);
        lnombre.setBounds(20, 70, 130, 30);
        getContentPane().add(tnombre);
        tnombre.setBounds(220, 70, 220, 30);

        ledad.setText("edad:");
        getContentPane().add(ledad);
        ledad.setBounds(20, 120, 90, 30);
        getContentPane().add(tedad);
        tedad.setBounds(240, 120, 160, 30);

        jLabel2.setText("correo electronico:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 180, 170, 30);
        getContentPane().add(tcorreo);
        tcorreo.setBounds(230, 170, 180, 40);

        jLabel3.setText("tiene carro propio (seleccione una opcion)");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 230, 260, 30);

        buttonGroup1.add(rsi);
        rsi.setText("SI");
        getContentPane().add(rsi);
        rsi.setBounds(290, 230, 60, 30);

        buttonGroup1.add(rno);
        rno.setText("NO");
        getContentPane().add(rno);
        rno.setBounds(380, 230, 98, 30);

        bregistrar.setText("REGISTRAR");
        bregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bregistrarActionPerformed(evt);
            }
        });
        getContentPane().add(bregistrar);
        bregistrar.setBounds(330, 350, 200, 60);

        bimprimir.setText("IMPRIMIR REGISTRO");
        bimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bimprimirActionPerformed(evt);
            }
        });
        getContentPane().add(bimprimir);
        bimprimir.setBounds(50, 350, 180, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        int cantidadNumeros = 5; // Cantidad de números aleatorios únicos a generar
        int maximo = 10; // Este es el número máximo (no se incluye)
        Random random = new Random();
        Set<Integer> numerosUnicos = new HashSet<>();

        while (numerosUnicos.size() < cantidadNumeros) {
            int numeroAleatorio = random.nextInt(maximo);
            numerosUnicos.add(numeroAleatorio);
        }
    }//GEN-LAST:event_formWindowActivated

    private void tnencuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnencuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnencuestaActionPerformed

    private void bregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bregistrarActionPerformed

        if (tnombre.getText().isEmpty() || tedad.getText().isEmpty() || tcorreo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todos los campos son obligatorios", "Error", JOptionPane.ERROR_MESSAGE);
            return;

        }
        int edad = Integer.parseInt(tedad.getText());
        if (edad < 18 || edad > 50) {
            JOptionPane.showMessageDialog(null, "La edad debe estar entre 18 y 50 años", "Alerta", JOptionPane.WARNING_MESSAGE); // Mostrar una alerta en caso de que la edad no esté dentro del rango permitido
        }
        
        clsencuesta.setEdad(Integer.parseInt(tedad.getText()));
        clsencuesta.setCorreoElectronico(tcorreo.getText());
        tcorreo.setText("");
        tedad.setText("");
        tnombre.setText("");
        tnencuesta.setText("");
        
          
    }//GEN-LAST:event_bregistrarActionPerformed

    private void bimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bimprimirActionPerformed
imprimir genero = new imprimir();
genero.setSize(800,800);
genero.setVisible(true);

    }//GEN-LAST:event_bimprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bimprimir;
    private javax.swing.JButton bregistrar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel ledad;
    private javax.swing.JLabel lnombre;
    private javax.swing.JRadioButton rno;
    private javax.swing.JRadioButton rsi;
    private javax.swing.JTextField tcorreo;
    private javax.swing.JTextField tedad;
    private javax.swing.JTextField tnencuesta;
    private javax.swing.JTextField tnombre;
    // End of variables declaration//GEN-END:variables
}
